(in-package :cl-repl)

;; TODO use constants instead of magic numbers

;; States
(defparameter *default-prompt-color* 40)
(defparameter *debugger-prompt-color* 9)
(defparameter *output-indicator-color* 9)
(defparameter *splash-color* 9)
(defparameter *condition-color* 9)
(defparameter *section-color* 21)
(defparameter *message-color* 248)

;; Syntaxic coloring
(defparameter *magic-syntax-color* 39)
(defparameter *string-syntax-color* 184)
(defparameter *variable-syntax-color* 118)
(defparameter *constant-syntax-color* 118)
(defparameter *lambda-syntax-color* 39)
(defparameter *definition-syntax-color* 118)
(defparameter *keyword-syntax-color* 39)
(defparameter *special-syntax-color* 197)
(defparameter *function-syntax-color* 197)
(defparameter *boolean-syntax-color* 197)
(defparameter *normal-syntax-color*  nil)


(defvar *color-schemes* (make-hash-table :test #'equal))

(defun find-color-scheme (name)
  (gethash name *color-schemes*))

(defmacro define-color-scheme (name (&optional parent) &body specs)
  `(setf (gethash ,name *color-schemes*) (cons ,parent ',specs)))

(defun set-color (spec color)
  (eval (read-from-string (format nil "(setf cl-repl::*~a-color* ~a)" spec color))))

(defun color-scheme (name)
  (let ((scheme (find-color-scheme name)))
    (when (car scheme)
      (color-scheme (car scheme)))
    (loop :for (spec color) :in (cdr scheme)
          :do (set-color spec color))))

(define-color-scheme "default" ()
  ("magic-syntax" 39)
  ("string-syntax" 184)
  ("variable-syntax" 118)
  ("constant-syntax" 118)
  ("lambda-syntax" 39)
  ("definition-syntax" 118)
  ("keyword-syntax" 39)
  ("special-syntax" 197)
  ("function-syntax" 197)
  ("boolean-syntax" 197)
  ("normal-syntax" nil)
  ("default-prompt" 40)
  ("debugger-prompt" 9)
  ("output-indicator" 9)
  ("condition" 9)
  ("section" 21)
  ("message" 248))

(define-color-scheme "off" ()
  ("magic-syntax" nil)
  ("string-syntax" nil)
  ("variable-syntax" nil)
  ("constant-syntax" nil)
  ("lambda-syntax" nil)
  ("definition-syntax" nil)
  ("keyword-syntax" nil)
  ("special-syntax" nil)
  ("function-syntax" nil)
  ("boolean-syntax" nil)
  ("normal-syntax" nil)
  ("default-prompt" nil)
  ("debugger-prompt" nil)
  ("output-indicator" nil)
  ("condition" nil)
  ("section" nil)
  ("message" nil))

